[package]
name = "infra-postgres"
version = "1.0.0"
edition = "2024"

[features]
default = []
strict = []

[dependencies]
domain-auth = { workspace = true }
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
webauthn-rs = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rs-repository-utils = { workspace = true, features = ["postgres", "health"] }
